document.addEventListener('DOMContentLoaded',function(){var nav=document.querySelector('nav');var onScroll=function(){if(window.scrollY>24){nav.classList.add('scrolled');}else{nav.classList.remove('scrolled');}};window.addEventListener('scroll',onScroll,{passive:true});onScroll();var tgl=document.querySelector('.nav-toggle'),menu=document.querySelector('.nav-r');if(tgl&&menu){tgl.addEventListener('click',function(){var o=menu.classList.toggle('open');nav.classList.toggle('menu-open',o);tgl.innerHTML=o?'\u2715':'\u2630';tgl.setAttribute('aria-expanded',o?'true':'false');document.body.style.overflow=o?'hidden':'';});menu.querySelectorAll('a').forEach(function(a){a.addEventListener('click',function(){menu.classList.remove('open');nav.classList.remove('menu-open');tgl.innerHTML='\u2630';tgl.setAttribute('aria-expanded','false');document.body.style.overflow='';});});}
var top=document.querySelector('.to-top');if(top){var tg=function(){if(window.scrollY>500){top.classList.add('show');}else{top.classList.remove('show');}};window.addEventListener('scroll',tg,{passive:true});tg();top.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'});});}});document.addEventListener('DOMContentLoaded',function(){var t=document.querySelector('.bx-toggle'),ix=document.querySelector('.bx-index');if(t&&ix){t.addEventListener('click',function(){var open=ix.classList.toggle('open');t.setAttribute('aria-expanded',open?'true':'false');t.innerHTML=open?'Show less &uarr;':'Show the full brand list &darr;';});}});document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('a.hero-cs-link[href="#work"]').forEach(function(a){a.addEventListener('click',function(e){e.preventDefault();var work=document.getElementById('work');if(!work)return;work.querySelectorAll('details.case').forEach(function(d){d.open=true;});work.scrollIntoView({behavior:'smooth',block:'start'});});});var expandWorkIfLinked=function(){if(window.location.hash==='#work'){var work=document.getElementById('work');if(!work)return;work.querySelectorAll('details.case').forEach(function(d){d.open=true;});work.scrollIntoView({behavior:'auto',block:'start'});}};expandWorkIfLinked();window.addEventListener('hashchange',expandWorkIfLinked);});
(function (C, A, L) { let p = function (a, ar) { a.q.push(ar); }; let d = C.document; C.Cal = C.Cal || function () { let cal = C.Cal; let ar = arguments; if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; } if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; if(typeof namespace === "string"){cal.ns[namespace] = cal.ns[namespace] || api;p(cal.ns[namespace], ar);p(cal, ["initNamespace", namespace]);} else p(cal, ar); return;} p(cal, ar); }; })(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init","project-fit-call",{origin:"https://app.cal.com"});
Cal.config=Cal.config||{};
Cal.config.forwardQueryParams=true;
Cal.ns["project-fit-call"]("ui",{"cssVarsPerTheme":{"light":{"cal-brand":"#21172F"},"dark":{"cal-brand":"#B49CE0"}},"hideEventTypeDetails":false,"layout":"month_view"});
Cal.ns["project-fit-call"]("on",{action:"bookingSuccessful",callback:function(e){window.location.href='/project-fit-call-booked';}});
Cal("init","opportunity-review",{origin:"https://app.cal.com"});
Cal.ns["opportunity-review"]("ui",{"cssVarsPerTheme":{"light":{"cal-brand":"#21172F"},"dark":{"cal-brand":"#B49CE0"}},"hideEventTypeDetails":false,"layout":"month_view"});
Cal.ns["opportunity-review"]("on",{action:"bookingSuccessful",callback:function(e){window.location.href='/opportunity-review-booked';}});
